USER FUNCTION PP07_LARGOVENT()

lnResul := 0

DO CASE
   CASE V_MODELO == "APAN"
      	PANEL := 0.34
	
   CASE V_MODELO == "PERS"  
      	PANEL := 0.32

ENDCASE

lnResul := (V_ALTO - 0.44 - (5 - U_PP02_FILAVENT())*PANEL - 0.40 - 0.010) / U_PP02_FILAVENT()     // LARGO DE CADA VENTANA

// ALTO - DESCUENTO - PANELES - PANEL SEPARADOR (GRANDE, MEDIANO Y 4 CHICOS) - SUJETADOR U

RETURN (lnResul)
